platform :ios, '13.0'

target 'ARFaceTreatmentSimulator' do
  use_frameworks!

  # Pods for ARFaceTreatmentSimulator
  pod 'ARKit'
  pod 'Alamofire' # For networking with the Replicate API
  pod 'SwiftyJSON' # For easier JSON handling

end